# Generated by Django 5.2.6 on 2025-11-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text="Tên định danh duy nhất của ý định, ví dụ: 'greeting', 'prod_ao_mu'", max_length=255, unique=True)),
                ('product_page_url', models.URLField(blank=True, help_text='(Tùy chọn) Link đến trang sản phẩm nếu đây là intent về sản phẩm.', max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Một mẫu câu hỏi của người dùng, ví dụ: 'Xin chào', 'áo mu giá bao nhiêu?'", max_length=512)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='intent_manager.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Một câu trả lời của bot, ví dụ: 'Chào bạn! Shop có thể giúp gì cho bạn?'", max_length=1024)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intent_manager.intent')),
            ],
        ),
    ]
