# Generated by Django 5.2.6 on 2025-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(help_text='ID của khách hàng từ bảng customer')),
                ('user_message', models.TextField(help_text='Tin nhắn của người dùng')),
                ('bot_response', models.JSONField(help_text='Đối tượng JSON phản hồi từ bot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Thời gian chat')),
            ],
        ),
    ]
